apiVersion: v1
kind: Service
metadata:
     name: web-service
spec:
    type: NodePort
    ports:
       - targetPort: 3000
         port: 30001
         nodePort: 30008
    selector:
        app: front-end
